name: Build and deploy bot to the cloud

on:
  push:
    branches:
    - main
env:
  PROJECT_ID: ${{secrets.RUN_PROJECT}}
  RUN_REGION: us-central1
  SERVICE_NAME: vwisemebot
  GITHUB_WORKSPACE: ${{ github.workspace }}
jobs:
  set-up-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
      
#     Set up GCloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
        
        
#     Build and push image to Google container registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
    
